- name: Build iOS
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -archivePath $RUNNER_TEMP/App.xcarchive \
          archive \
          CODE_SIGN_STYLE=Manual \
          PROVISIONING_PROFILE_SPECIFIER="LePassDunInstant_Distribution" \
          CODE_SIGN_IDENTITY="Apple Distribution" \
          DEVELOPMENT_TEAM="YDVHWA9LU8"
